disabled = false
locale = "en"
label = "English"
weight = 1
title = "Hildelith the Weaver"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"

[params.author]
  name = "Hildelith the Weaver"
  email = "info@hildeliththeweaver.com"
  image = "img/logo.png"
  imageQuality = 96
  headline = "Historical fibrecraft recreations and exploration"
  bio = "I'm a historical reenactor and fibre enthusiast, with a particular love of weaving"
  links = [
    { email = "mailto:info@hildeliththeweaver.com" },
    { instagram = "https://instagram.com/hildeliththeweaver" }
  ]
